var express = require('express');
var router = express.Router();

const nameList = [
{ 'id': 1, 'term': 'Continuous Integration (CI):', 'des': ' CI is a development practice where code changes are automatically integrated into a shared repository multiple times a day. It allows teams to detect and address integration issues early, ensuring a consistent codebase.', 'refe': 'https://www.atlassian.com/continuous-delivery/continuous-integration'},
{'id': 2, 'term': 'Continuous Deployment (CD)', 'des': 'CD is the process of automatically deploying code changes to production after successful CI and passing automated tests. It ensures a streamlined and automated software delivery pipeline.', 'refe': 'https://www.atlassian.com/continuous-delivery/principles/continuous-integration-vs-delivery-vs-deployment'},
{'id': 3, 'term': 'Infrastructure as Code (IaC)', 'des': ' IaC is the practice of managing and provisioning infrastructure through machine-readable configuration files. It enables version control, scalability, and consistency in infrastructure management.', 'refe': 'https://www.hashicorp.com/resources/what-is-infrastructure-as-code'},
{'id': 4, 'term': 'DevOpss', 'des': 'DevOps is a cultural and collaborative approach that fosters close cooperation between development and operations teams throughout the software development life cycle. It aims to improve software delivery speed and reliability.', 'refe': 'https://aws.amazon.com/devops/what-is-devops/'},
{'id': 5, 'term': 'Microservices', 'des': 'Microservices is an architectural pattern where a software application is divided into small, loosely coupled services that can be developed, deployed, and scaled independently. It enables greater flexibility and modularity.', 'refe': 'https://microservices.io/'},
{'id': 6, 'term': 'Docker', 'des': 'Docker is a containerization platform that allows developers to package applications and their dependencies into lightweight containers. Containers ensure consistent environments and facilitate portability across different systems.', 'refe': 'https://www.docker.com/what-docker'},
{'id': 7, 'term': 'Kubernetes', 'des': ' Kubernetes is an open-source container orchestration platform that automates the deployment, scaling, and management of containerized applications. It simplifies container management at scale.', 'refe': 'https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/'},
{'id': 8, 'term': 'Monitoring and Observability', 'des': 'Monitoring involves tracking the performance and health of systems, applications, and infrastructure. Observability takes monitoring further, emphasizing understanding system behavior through logs, metrics, and traces.', 'refe': 'https://www.oreilly.com/library/view/monitoring-and-observability/9781492076848/'},
{'id': 9, 'term': 'Continuous Monitoring', 'des': ' Continuous Monitoring is an ongoing process of gathering and analyzing real-time data to ensure system performance, security, and compliance. It helps detect issues proactively and improves overall system reliability.', 'refe': 'https://www.csoonline.com/article/2130012/what-is-continuous-monitoring-and-why-is-it-important.html'},
{'id': 10, 'term': 'Configuration Management', 'des': ' Configuration Management involves managing and maintaining the configuration settings and parameters of software and infrastructure components. It ensures consistency across different environments and reduces manual errors.', 'refe': 'https://www.atlassian.com/continuous-delivery/configuration-management'},
{'id': 11, 'term': 'Branching', 'des': 'Branching is the process of creating separate branches of code that developers work on.', 'refe': 'https://www.heptabit.at/blog/devops/devops-branching-strategy-what-is-it-how-it-works#:~:text=Branching%20is%20the%20process%20of,be%20complicated%20and%20get%20messy.'},
{'id': 12, 'term': 'Commit', 'des': 'In version control systems, a commit is an operation which sends the latest changes of the source code to the repository, making these changes part of the head revision of the repository.', 'refe': 'https://en.wikipedia.org/wiki/Commit_(version_control)#:~:text=In%20version%20control%20systems%2C%20a,head%20revision%20of%20the%20repository.'},
{'id': 13, 'term': 'Capacity Test', 'des': 'Capacity Testing exercises the system to check if the application and infrastructure can actually take on the amount of traffic that they were designed to handle without compromising user experience.', 'refe': 'https://www.radview.com/blog/all-you-need-to-know-about-capacity-testing/'},
{'id': 14, 'term': 'Containerization', 'des': 'Containerization entails placing a software component and its environment, dependencies, and configuration, into an isolated unit called a container. ', 'refe': 'https://www.aquasec.com/cloud-native-academy/docker-container/container-devops/#:~:text=What%20Does%20Containerization%20Mean%20for,%2Dpremises%20or%20cloud%2Dbased.'},
{'id': 15, 'term': 'Deployment Pipeline', 'des': 'A DevOps pipeline is the set of automated processes and tools that the development and operations teams use to compile, construct, test, and deploy software code faster and easier.', 'refe': 'https://www.simplilearn.com/what-is-pipeline-in-devops-tools-implementation-article'},
{'id': 16, 'term': 'Event-Driven Architecture', 'des': 'An event-driven architecture uses events to trigger and communicate between decoupled services and is common in modern applications built with microservices.', 'refe': 'https://aws.amazon.com/event-driven-architecture/#:~:text=An%20event%2Ddriven%20architecture%20uses,on%20an%20e%2Dcommerce%20website.'},
{'id': 17, 'term': 'Test Automation', 'des': 'Test automation decreases the amount of human intervention in the testing process.', 'refe': 'https://www.cprime.com/resources/blog/test-automation-and-devops-what-you-need-to-know/#:~:text=What%20Is%20Test%20Automation%3F,detect%20bugs%20and%20save%20time'},
{'id': 18, 'term': 'Cluster', 'des': 'Cluster is a group of servers and other resources that act like a single system and enable high availability, load balancing and parallel processing.', 'refe': 'https://www.techtarget.com/whatis/definition/cluster#:~:text=In%20a%20computer%20system%2C%20a,load%20balancing%20and%20parallel%20processing.'},
{'id': 19, 'term': 'ElasticSearch', 'des': 'Elasticsearch is a distributed, free and open search and analytics engine for all types of data, including textual, numerical, geospatial, structured, and unstructured.', 'refe': 'https://www.elastic.co/what-is/elasticsearch'},
{'id': 20, 'term': 'Autonomy', 'des': 'Autonomy refers to the ability to make decisions independently, without having to wait on or defer to someone higher up in the hierarchy.', 'refe': 'https://www.plutora.com/devops-at-scale/terminology-glossary'},
];

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'SIT722 DevOps Glossary', sub: 'ABC', names: nameList  });
});

module.exports = router;
