var express = require('express');
var router = express.Router();

const nameList = [
{ 'id': 1, 'term': 'Continuous Integration (CI):', 'des': ' CI is a development practice where code changes are automatically integrated into a shared repository multiple times a day. It allows teams to detect and address integration issues early, ensuring a consistent codebase.', 'refe': 'https://www.atlassian.com/continuous-delivery/continuous-integration'},
{'id': 2, 'term': 'Continuous Deployment (CD)', 'des': 'CD is the process of automatically deploying code changes to production after successful CI and passing automated tests. It ensures a streamlined and automated software delivery pipeline.', 'refe': 'https://www.atlassian.com/continuous-delivery/principles/continuous-integration-vs-delivery-vs-deployment'},
{'id': 3, 'term': 'Infrastructure as Code (IaC)', 'des': ' IaC is the practice of managing and provisioning infrastructure through machine-readable configuration files. It enables version control, scalability, and consistency in infrastructure management.', 'refe': 'https://www.hashicorp.com/resources/what-is-infrastructure-as-code'},
{'id': 4, 'term': 'DevOpss', 'des': 'DevOps is a cultural and collaborative approach that fosters close cooperation between development and operations teams throughout the software development life cycle. It aims to improve software delivery speed and reliability.', 'refe': 'https://aws.amazon.com/devops/what-is-devops/'},
{'id': 5, 'term': 'Microservices', 'des': 'Microservices is an architectural pattern where a software application is divided into small, loosely coupled services that can be developed, deployed, and scaled independently. It enables greater flexibility and modularity.', 'refe': 'https://microservices.io/'},
{'id': 6, 'term': 'Docker', 'des': 'Docker is a containerization platform that allows developers to package applications and their dependencies into lightweight containers. Containers ensure consistent environments and facilitate portability across different systems.', 'refe': 'https://www.docker.com/what-docker'},
{'id': 7, 'term': 'Kubernetes', 'des': ' Kubernetes is an open-source container orchestration platform that automates the deployment, scaling, and management of containerized applications. It simplifies container management at scale.', 'refe': 'https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/'},
{'id': 8, 'term': 'Monitoring and Observability', 'des': 'Monitoring involves tracking the performance and health of systems, applications, and infrastructure. Observability takes monitoring further, emphasizing understanding system behavior through logs, metrics, and traces.', 'refe': 'https://www.oreilly.com/library/view/monitoring-and-observability/9781492076848/'},
{'id': 9, 'term': 'Continuous Monitoring', 'des': ' Continuous Monitoring is an ongoing process of gathering and analyzing real-time data to ensure system performance, security, and compliance. It helps detect issues proactively and improves overall system reliability.', 'refe': 'https://www.csoonline.com/article/2130012/what-is-continuous-monitoring-and-why-is-it-important.html'},
{'id': 10, 'term': 'Configuration Management', 'des': ' Configuration Management involves managing and maintaining the configuration settings and parameters of software and infrastructure components. It ensures consistency across different environments and reduces manual errors.', 'refe': 'https://www.atlassian.com/continuous-delivery/configuration-management'},
{'id': 11, 'term': 'Branching', 'des': 'Branching is the process of creating separate branches of code that developers work on.', 'refe': 'https://www.heptabit.at/blog/devops/devops-branching-strategy-what-is-it-how-it-works#:~:text=Branching%20is%20the%20process%20of,be%20complicated%20and%20get%20messy.'},
{'id': 12, 'term': 'Commit', 'des': 'In version control systems, a commit is an operation which sends the latest changes of the source code to the repository, making these changes part of the head revision of the repository.', 'refe': 'https://en.wikipedia.org/wiki/Commit_(version_control)#:~:text=In%20version%20control%20systems%2C%20a,head%20revision%20of%20the%20repository.'},
{'id': 13, 'term': 'Capacity Test', 'des': 'Capacity Testing exercises the system to check if the application and infrastructure can actually take on the amount of traffic that they were designed to handle without compromising user experience.', 'refe': 'https://www.radview.com/blog/all-you-need-to-know-about-capacity-testing/'},
{'id': 14, 'term': 'Containerization', 'des': 'Containerization entails placing a software component and its environment, dependencies, and configuration, into an isolated unit called a container. ', 'refe': 'https://www.aquasec.com/cloud-native-academy/docker-container/container-devops/#:~:text=What%20Does%20Containerization%20Mean%20for,%2Dpremises%20or%20cloud%2Dbased.'},
{'id': 15, 'term': 'Deployment Pipeline', 'des': 'A DevOps pipeline is the set of automated processes and tools that the development and operations teams use to compile, construct, test, and deploy software code faster and easier.', 'refe': 'https://www.simplilearn.com/what-is-pipeline-in-devops-tools-implementation-article'},
{'id': 16, 'term': 'Event-Driven Architecture', 'des': 'An event-driven architecture uses events to trigger and communicate between decoupled services and is common in modern applications built with microservices.', 'refe': 'https://aws.amazon.com/event-driven-architecture/#:~:text=An%20event%2Ddriven%20architecture%20uses,on%20an%20e%2Dcommerce%20website.'},
{'id': 17, 'term': 'Test Automation', 'des': 'Test automation decreases the amount of human intervention in the testing process.', 'refe': 'https://www.cprime.com/resources/blog/test-automation-and-devops-what-you-need-to-know/#:~:text=What%20Is%20Test%20Automation%3F,detect%20bugs%20and%20save%20time'},
{'id': 18, 'term': 'Cluster', 'des': 'Cluster is a group of servers and other resources that act like a single system and enable high availability, load balancing and parallel processing.', 'refe': 'https://www.techtarget.com/whatis/definition/cluster#:~:text=In%20a%20computer%20system%2C%20a,load%20balancing%20and%20parallel%20processing.'},
{'id': 19, 'term': 'ElasticSearch', 'des': 'Elasticsearch is a distributed, free and open search and analytics engine for all types of data, including textual, numerical, geospatial, structured, and unstructured.', 'refe': 'https://www.elastic.co/what-is/elasticsearch'},
{'id': 20, 'term': 'Autonomy', 'des': 'Autonomy refers to the ability to make decisions independently, without having to wait on or defer to someone higher up in the hierarchy.', 'refe': 'https://www.plutora.com/devops-at-scale/terminology-glossary'},
{'id': 21, 'term': 'Containers', 'des': 'Containerization, a logical progression of virtualization, virtualizes the operating system and treats each application as its own conceptually different server.', 'refe': 'https://www.plutora.com/devops-at-scale/terminology-glossary'},
{'id': 22, 'term': 'Containers-as-a-Service', 'des': 'Cloud service model that offers container-based virtualization with container engines, orchestration and compute resources.', 'refe': 'https://www.plutora.com/devops-at-scale/terminology-glossary'},
{'id': 23, 'term': 'DevSecOps', 'des': 'Instead of leaving security to the very end, DevSecOps integrates security into all phases of the software development process.', 'refe': 'https://www.plutora.com/devops-at-scale/terminology-glossary'},
{'id': 24, 'term': 'Machine Learning', 'des': 'A subfield of artificial intelligence known as machine learning enables computers to learn without explicit programming.', 'refe': 'https://www.plutora.com/devops-at-scale/terminology-glossary'},
{'id': 25, 'term': 'Microservices Architecture', 'des': 'A fresh approach to software design that divides large systems into loosely connected services that may be independently created, deployed, and maintained.', 'refe': 'https://www.plutora.com/devops-at-scale/terminology-glossary'},
{'id': 26, 'term': 'Open Source', 'des': 'software that permits unrestricted usage, sharing, and modification of its original source code.', 'refe': 'https://www.plutora.com/devops-at-scale/terminology-glossary'},
{'id': 27, 'term': 'Rollback', 'des': 'the action of reverting an item or application to a previous version.', 'refe': 'https://medium.com/@bharghavyerravalli/rollback-and-its-importance-in-a-devops-world-21d486738760'},
{'id': 28, 'term': 'Root Cause Analysis', 'des': 'Root cause analysis is a methodical process for determining the fundamental reasons of issues or events.', 'refe': 'https://www.spiceworks.com/tech/devops/articles/what-is-root-cause-analysis/#:~:text=Root%20cause%20analysis%20(RCA)%20is,%2C%20DevOps%2C%20and%20infrastructure%20management.'},
{'id': 29, 'term': 'Scrum', 'des': 'Scrum is an agile project management framework that divides the work that needs to be done into discrete pieces and works on them during time blocks called sprints.', 'refe': 'https://www.plutora.com/devops-at-scale/terminology-glossary'},
{'id': 30, 'term': 'Mean Time Between Failures', 'des': 'measured by average the intervals between system failures and is used to assess a system or component reliability.', 'refe': 'https://medium.com/@DZoneInc/48-devops-terms-you-should-know-a-devops-glossary-37e60fd23752'},
{'id': 31, 'term': 'Source Code Management', 'des': 'A source code repositorys alterations are tracked using source code management (SCM). When integrating updates from several contributors, SCM keeps a running history of modifications to a code base and assists in resolving disputes.', 'refe': 'https://www.atlassian.com/git/tutorials/source-code-management#:~:text=Source%20code%20management%20(SCM)%20is,merging%20updates%20from%20multiple%20contributors.'},
{'id': 32, 'term': 'Staging Environment', 'des': 'An environment used to test programmes, builds, and updates to make sure everything functions properly before deployment that is almost a perfect reproduction of a production environment.', 'refe': 'https://www.plutora.com/devops-at-scale/terminology-glossary'},
{'id': 33, 'term': 'User Acceptance Testing (UAT)', 'des': 'User acceptability testing (UAT), also known as acceptance testing, ascertains if a system fulfils authorised entity requirements, business requirements, and user demands.', 'refe': 'https://opensource.com/article/19/4/devops-pipeline-acceptance-testing#:~:text=Acceptance%20testing%2C%20also%20called%20user,software%20development%20lifecycle%20(SDLC).'},
{'id': 34, 'term': 'Load Balancing', 'des': 'Network traffic is divided equally across a pool of resources used to serve an application through a process called load balancing.', 'refe': 'https://aws.amazon.com/what-is/load-balancing/#:~:text=Load%20balancing%20is%20the%20method,a%20fast%20and%20reliable%20manner.'},
{'id': 35, 'term': 'Self-Healing Kubernetes', 'des': 'The open-source Kubernetes system has the capability of self-healing.Kubernetes re-deploys the containerized app or application component in order to maintain the intended state if it fails or goes down. Self-healing is a standard feature of Kubernetes.', 'refe': 'https://www.educative.io/answers/what-is-self-healing-in-kubernetes'},
{'id': 36, 'term': 'Pods', 'des': 'Pods are the smallest deployable units of computing that you can create and manage in Kubernetes.', 'refe': 'https://kubernetes.io/docs/concepts/workloads/pods/'},
{'id': 37, 'term': 'Terraform', 'des': 'Terraform is a tool for managing cloud infrastructure that was created by Hashicorp. Infrastructure as Code is used by Terraform to automate the installation and maintenance of infrastructure.', 'refe': 'https://octopus.com/devops/glossary/'},
{'id': 38, 'term': 'container registry', 'des': 'A container registry is a collection of repositories made to store container images.', 'refe': 'https://www.techtarget.com/searchcloudcomputing/definition/container-registry'},
{'id': 39, 'term': 'kubectl', 'des': 'Using the Kubernetes API, Kubernetes offers a command line tool for interacting with a cluster control plane. The name of this tool is kubectl.', 'refe': 'https://kubernetes.io/docs/reference/kubectl/'},
{'id': 40, 'term': 'Azure CLI', 'des': 'A cross-platform command-line tool called the Azure Command-Line Interface (CLI) allows users to login to Azure and run administrative commands on its resources.', 'refe': 'https://learn.microsoft.com/en-us/cli/azure/what-is-azure-cli'},

];

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'SIT722 DevOps Glossary', sub: 'ABC', names: nameList  });
});

module.exports = router;
